### ISSUE TITLE
Examples for how to use the FFI to capture parameters returned from mouse `on` events?

### ISSUE THREAD

**Issue by o1lo01ol1o** [obsidiansystems/reflex-dom-echarts#3]
I'm happy to have found this library despite the relatively small amount of api coverage it offers.  Could anyone point me to `reflex-dom` code that might inform me how to go about capturing data from an `echart` callback?

For example [this uses the the `.on` member to return parameters of clicks (and add those as new datapoints on the graph)](https://echarts.apache.org/examples/en/editor.html?c=line-pen).  If I had some data for which I know that `params.foo` was an `Int`, how might I use the JSM to observe `params.foo :: Int` as an `Event t Int`?

**Comment by o1lo01ol1o** [comment]
Figured out a solution via https://github.com/obsidiansystems/echarts-jsdom/blob/master/src/ECharts.hs#L49

**Comment by 3noch** [comment]
Awesome thanks for the feedback.
